export const instrumentDescription = {
    stocks: "Investing in stocks means purchasing shares of ownership in a company. Stocks are a common type of investment that offer the potential for high returns, but they also come with higher risk. Historically, stocks have provided an average annual return of around 7-10%. They represent ownership in companies ranging from small startups to large multinational corporations. Stocks can be traded on stock exchanges and their value can fluctuate based on market conditions, company performance, and economic factors.",

    etf: "ETFs, or Exchange-Traded Funds, are investment funds that hold assets such as stocks, bonds, or commodities. They are traded on stock exchanges similar to individual stocks. ETFs offer diversification by holding a basket of assets, which can help reduce risk compared to investing in individual securities. They typically have lower expense ratios compared to mutual funds. ETFs can track various market indexes or specific sectors, providing exposure to different segments of the market. They are a popular choice for investors seeking diversified exposure to various asset classes.",

    gold: "Investing in gold is a popular way to diversify a portfolio and hedge against economic uncertainty. Gold has been considered a store of value for centuries and is often viewed as a safe haven during times of market volatility. It can act as a hedge against inflation and currency fluctuations. Historically, gold has provided an average annual return of around 5-7%. Investors can buy gold in various forms, including physical bullion, coins, bars, and through gold exchange-traded funds (ETFs). Gold prices can be influenced by factors such as supply and demand, geopolitical events, and changes in interest rates.",

    ipo: "An Initial Public Offering (IPO) occurs when a private company becomes publicly traded by offering its shares to the general public for the first time. IPOs provide an opportunity for investors to buy shares in a company before they start trading on a stock exchange. Investing in IPOs can be attractive due to the potential for significant returns if the company experiences rapid growth. However, IPOs also carry higher risk as the company may be relatively unknown and lack a track record of financial performance. It's essential for investors to conduct thorough research before investing in an IPO.",

    mutualFund: "Mutual funds are investment vehicles that pool money from multiple investors to invest in a diversified portfolio of stocks, bonds, or other securities. They are managed by professional fund managers who make investment decisions on behalf of the investors. Mutual funds offer diversification, liquidity, and professional management. They are available in various types, including equity funds, bond funds, index funds, and balanced funds. Mutual funds typically charge fees, such as expense ratios and sales loads, which can impact overall returns. Historically, mutual funds have provided average annual returns ranging from 5-8%, depending on the fund type and market conditions."
};